# BUSTEDS-MH configuration yaml


# Simulations for Shultz-Sackton
DataDirectory: /home/aglucaci/BUSTEDS-MH/data/sims/null
SubDirectory: "null-0.25"
FileEnding: "*.*"
OutputDirectory: /home/aglucaci/BUSTEDS-MH/analysis/Simulations-Shultz-Sackton

# Defaults
BUSTEDSMHBF: /home/aglucaci/hyphy-analyses/BUSTED-MH/BUSTED-MH.bf
